/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FilterPreset } from './Preset';
import { createDefaultColorGrade, createDefaultHslBand } from '../color/ColorGrade';

function baseGrade() {
  return createDefaultColorGrade();
}

export const FILTER_CATEGORIES_METADATA: {
  id: string;
  label: string;
  icon: string;
  tagline: string;
  accent: string;
}[] = [
  { id: 'for_you', label: 'For You', icon: 'Sparkles', tagline: 'Personalized AI & creator recommendations', accent: 'from-amber-400 to-orange-500' },
  { id: 'trending', label: 'Trending', icon: 'Flame', tagline: 'Most popular viral video creator grades', accent: 'from-rose-500 to-pink-500' },
  { id: 'new', label: 'New', icon: 'Zap', tagline: 'Freshly dropped cinema grades and seasonal looks', accent: 'from-emerald-400 to-teal-500' },
  { id: 'veecut_originals', label: 'VeeCut Originals', icon: 'Award', tagline: 'Signature studio color grades crafted for perfection', accent: 'from-amber-500 to-yellow-500' },
  { id: 'cinematic', label: 'Cinematic', icon: 'Film', tagline: 'Hollywood anamorphic blockbusters & widescreen looks', accent: 'from-sky-500 to-blue-600' },
  { id: 'portrait', label: 'Portrait', icon: 'Smile', tagline: 'Flattering warm glow, golden hour & porcelain skin', accent: 'from-pink-400 to-rose-500' },
  { id: 'travel', label: 'Travel', icon: 'Compass', tagline: 'Vibrant azure skies, sunlit coasts & wanderlust punch', accent: 'from-cyan-400 to-blue-500' },
  { id: 'vlog', label: 'Vlog', icon: 'Video', tagline: 'Clean, radiant lifestyle & natural creator broadcast', accent: 'from-purple-400 to-indigo-500' },
  { id: 'sports', label: 'Sports', icon: 'Activity', tagline: 'High dynamic range, punchy contrast & action clarity', accent: 'from-orange-500 to-red-600' },
  { id: 'gaming', label: 'Gaming', icon: 'Gamepad2', tagline: 'Cyberpunk neon highlights, dark abyss & synth pop', accent: 'from-fuchsia-500 to-purple-600' },
  { id: 'vintage', label: 'Vintage & Retro', icon: 'Clock', tagline: '70s Kodachrome, 80s Synthwave & 90s analog camcorders', accent: 'from-yellow-500 to-amber-600' },
  { id: 'black_white', label: 'Black & White', icon: 'Maximize2', tagline: 'High contrast silver gelatin & moody film noir drama', accent: 'from-zinc-400 to-zinc-600' },
  { id: 'social', label: 'Social & Reels', icon: 'Share2', tagline: 'Punchy eye-catching hooks for Reels, Shorts & TikTok', accent: 'from-pink-500 to-rose-500' },
  { id: 'film', label: 'Film & Analog', icon: 'Camera', tagline: 'Kodak Portra, Fuji Velvia & authentic celluloid grain', accent: 'from-emerald-500 to-teal-600' },
  { id: 'urban', label: 'Urban & Street', icon: 'Briefcase', tagline: 'Cyberpunk neo-Tokyo, concrete street & metro steel', accent: 'from-cyan-500 to-blue-500' },
  { id: 'mood', label: 'Moody & Dark', icon: 'CloudRain', tagline: 'Atmospheric haze, Nordic mist & twilight shadows', accent: 'from-purple-500 to-indigo-600' },
  { id: 'lifestyle', label: 'Food & Lifestyle', icon: 'ShoppingBag', tagline: 'Warm bistro cafes, golden bakeries & pastel brunch', accent: 'from-amber-400 to-yellow-500' },
  { id: 'night', label: 'Night & Low Light', icon: 'Moon', tagline: 'Sodium vapor streets, midnight blues & club neon', accent: 'from-indigo-500 to-violet-600' },
  { id: 'minimal', label: 'Clean & Minimal', icon: 'ShieldCheck', tagline: 'Nordic pure whites, subtle muted tones & clean studio', accent: 'from-slate-300 to-slate-500' },
  { id: 'stylized', label: 'Stylized & Sci-Fi', icon: 'Cpu', tagline: 'Anime pop dynamic, solar flare & thermal spectrums', accent: 'from-fuchsia-500 to-purple-600' },
  { id: 'duotone', label: 'Duotone & Pop', icon: 'Layers', tagline: 'Vibrant dual-color channel splits & bold graphic looks', accent: 'from-violet-500 to-pink-500' },
  { id: 'my_filters', label: 'My Custom Filters', icon: 'Bookmark', tagline: 'Your personally crafted and saved filter looks', accent: 'from-cyan-400 to-teal-500' },
  { id: 'favorites', label: 'Favorites', icon: 'Heart', tagline: 'Quick access to your bookmarked favorite looks', accent: 'from-rose-500 to-red-600' },
];

export const BUILT_IN_FILTER_PRESETS: FilterPreset[] = [
  // -------------------------------------------------------------------------
  // 5 PROFESSIONAL CINEMATIC FILTERS
  // -------------------------------------------------------------------------
  {
    id: 'fuji-velvia-50',
    name: 'Fuji Velvia 50',
    category: 'film',
    description: 'Legendary high-saturation slide film look known for rich ocean blues, vivid forest greens, and punchy landscape contrast.',
    author: 'VeeCut Pro Cinema',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.98,
    popularityScore: 99,
    usageCount: 480000,
    isTrending: true,
    isNew: true,
    tags: ['fuji', 'velvia', 'slide film', 'landscape', 'vivid', 'nature', 'cinematic'],
    previewGradient: 'linear-gradient(135deg, #0284c7 0%, #059669 50%, #d97706 100%)',
    colorGrade: {
      ...baseGrade(),
      brightness: 2,
      brilliance: 15,
      contrast: 18,
      highlights: -8,
      shadows: 6,
      saturation: 20,
      vibrance: 28,
      warmth: 4,
      temperature: 4,
      tint: 1,
      sharpness: 10,
      sharpen: 10,
      definition: 18,
      clarity: 12,
      vignette: 5,
    },
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'kodak-ektar-100',
    name: 'Kodak Ektar 100',
    category: 'film',
    description: 'Ultra-fine grain color negative film with razor-sharp micro-contrast, vibrant saturated colors, and smooth highlight rolloff.',
    author: 'VeeCut Pro Cinema',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.97,
    popularityScore: 98,
    usageCount: 410000,
    isTrending: true,
    isNew: true,
    tags: ['kodak', 'ektar', 'fine grain', 'sharp', 'landscape', 'cinematic', 'color negative'],
    previewGradient: 'linear-gradient(135deg, #ea580c 0%, #0284c7 50%, #ca8a04 100%)',
    colorGrade: {
      ...baseGrade(),
      brightness: 3,
      brilliance: 15,
      contrast: 18,
      highlights: -8,
      shadows: 6,
      saturation: 12,
      vibrance: 20,
      warmth: 4,
      temperature: 4,
      tint: 1,
      sharpness: 16,
      sharpen: 16,
      definition: 22,
      clarity: 14,
      vignette: 5,
    },
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'fuji-eterna-250d',
    name: 'Fuji Eterna 250D',
    category: 'cinematic',
    description: 'Iconic cinematic motion picture stock with gentle highlight roll-off, soft pastel undertones, open shadow latitude, and subtle greens.',
    author: 'VeeCut Pro Cinema',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.96,
    popularityScore: 97,
    usageCount: 395000,
    isTrending: true,
    isNew: true,
    tags: ['fuji', 'eterna', 'motion picture', 'drama', 'pastel', 'film', 'cinematic'],
    previewGradient: 'linear-gradient(135deg, #0d9488 0%, #64748b 50%, #d97706 100%)',
    colorGrade: {
      ...baseGrade(),
      brightness: 5,
      brilliance: 14,
      contrast: -4,
      highlights: -15,
      shadows: 12,
      saturation: -6,
      vibrance: 8,
      warmth: 3,
      temperature: 3,
      tint: -1,
      sharpness: 8,
      sharpen: 8,
      definition: 12,
      clarity: 6,
      vignette: 2,
    },
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'kodak-2383',
    name: 'Kodak 2383',
    category: 'cinematic',
    description: 'The gold standard Hollywood theatrical print film stock used in master grades for decades. High contrast, warm golden skin tones, and rich deep film blacks.',
    author: 'VeeCut Pro Cinema',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.99,
    popularityScore: 100,
    usageCount: 650000,
    isTrending: true,
    isNew: true,
    tags: ['kodak', '2383', 'print film', 'hollywood', 'master', 'blockbuster', 'cinematic'],
    previewGradient: 'linear-gradient(135deg, #d97706 0%, #1e293b 50%, #b45309 100%)',
    colorGrade: {
      ...baseGrade(),
      brightness: 2,
      brilliance: 10,
      contrast: 24,
      highlights: -12,
      shadows: 4,
      saturation: 10,
      vibrance: 16,
      warmth: 5,
      temperature: 5,
      tint: 2,
      sharpness: 10,
      sharpen: 10,
      definition: 16,
      clarity: 12,
      vignette: 7,
    },
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'cinematic-nature',
    name: 'Cinematic Nature',
    category: 'cinematic',
    description: 'Modern documentary and high-end natural history look. Lush emerald foliage, balanced sky luminances, preserved shadow dynamic range, and organic depth.',
    author: 'VeeCut Pro Cinema',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.97,
    popularityScore: 98,
    usageCount: 420000,
    isTrending: true,
    isNew: true,
    tags: ['nature', 'cinematic', 'landscape', 'documentary', 'emerald', 'sky', 'outdoor'],
    previewGradient: 'linear-gradient(135deg, #059669 0%, #0284c7 50%, #15803d 100%)',
    colorGrade: {
      ...baseGrade(),
      brightness: 5,
      brilliance: 16,
      contrast: 10,
      highlights: -14,
      shadows: 12,
      saturation: 8,
      vibrance: 18,
      warmth: 2,
      temperature: 2,
      tint: -1,
      sharpness: 10,
      sharpen: 10,
      definition: 16,
      clarity: 8,
      vignette: 3,
    },
    createdAt: '2025-02-01T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 0. VEECUT ORIGINALS (10 Signature Studio Presets)
  // -------------------------------------------------------------------------
  {
    id: 'veecut_gold_rays',
    name: 'Gold Rays',
    category: 'veecut_originals',
    description: 'Golden sunburst anamorphic look with luminous warm highlights, lifted amber midtones, and subtle halation glow.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.98,
    popularityScore: 100,
    usageCount: 520000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'gold', 'warm', 'rays', 'cinematic', 'sunburst'],
    previewGradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 40%, #fbbf24 80%, #78350f 100%)',
    lutId: 'gold-rays',
    colorGrade: {
      ...baseGrade(),
      temperature: 32,
      tint: -8,
      contrast: 1.18,
      saturation: 1.15,
      brilliance: 25,
      highlights: -12,
      shadows: 18,
      vignette: 0.22,
      grain: 15,
      wheels: {
        lift: { r: 0.08, g: 0.04, b: -0.05, y: -0.02 },
        gamma: { r: 0.12, g: 0.06, b: -0.08, y: 0.04 },
        gain: { r: 0.24, g: 0.14, b: -0.12, y: 0.08 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_navy_gold',
    name: 'Navy Gold',
    category: 'veecut_originals',
    description: 'Signature modern blockbuster split-tone balancing deep midnight navy shadows against warm honey-gold skin tones.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.96,
    popularityScore: 99,
    usageCount: 480000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'navy', 'gold', 'split-tone', 'blockbuster'],
    previewGradient: 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 35%, #d97706 75%, #fbbf24 100%)',
    lutId: 'navy-gold',
    colorGrade: {
      ...baseGrade(),
      temperature: 16,
      tint: 6,
      contrast: 1.32,
      saturation: 1.2,
      highlights: -15,
      shadows: 10,
      blacks: -8,
      fade: 5,
      vignette: 0.28,
      wheels: {
        lift: { r: -0.18, g: -0.05, b: 0.22, y: -0.06 },
        gamma: { r: 0.04, g: -0.02, b: 0.02, y: 0.0 },
        gain: { r: 0.22, g: 0.12, b: -0.15, y: 0.06 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_cinematic_gold',
    name: 'Cinematic Gold',
    category: 'veecut_originals',
    description: 'Luxurious 35mm Hollywood film stock with rich golden warmth, organic shadow rolloff, and creamy highlight compression.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.97,
    popularityScore: 98,
    usageCount: 430000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'cinematic', 'gold', 'film', 'luxury', '35mm'],
    previewGradient: 'linear-gradient(135deg, #78350f 0%, #b45309 40%, #fbbf24 80%, #fef3c7 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 24,
      tint: -4,
      contrast: 1.25,
      saturation: 1.12,
      clarity: 15,
      sharpen: 12,
      highlights: -18,
      shadows: 12,
      whites: -6,
      fade: 8,
      grain: 22,
      vignette: 0.24,
      wheels: {
        lift: { r: 0.04, g: 0.02, b: -0.03, y: -0.02 },
        gamma: { r: 0.08, g: 0.04, b: -0.04, y: 0.02 },
        gain: { r: 0.18, g: 0.11, b: -0.08, y: 0.05 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_deep_cinema',
    name: 'Deep Cinema',
    category: 'veecut_originals',
    description: 'High-contrast dramatic cinema grade featuring deep crushed shadow tones, desaturated foliage, and icy anamorphic highlights.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.94,
    popularityScore: 97,
    usageCount: 390000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'deep', 'cinema', 'contrast', 'moody', 'anamorphic'],
    previewGradient: 'linear-gradient(135deg, #020617 0%, #0f172a 40%, #1e293b 80%, #38bdf8 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -10,
      tint: 12,
      contrast: 1.38,
      saturation: 0.92,
      clarity: 24,
      highlights: 15,
      shadows: -22,
      blacks: -15,
      fade: 12,
      vignette: 0.35,
      grain: 18,
      wheels: {
        lift: { r: -0.12, g: -0.08, b: 0.05, y: -0.08 },
        gamma: { r: -0.02, g: 0.02, b: 0.04, y: 0.0 },
        gain: { r: 0.05, g: 0.08, b: 0.18, y: 0.04 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_clean_film',
    name: 'Clean Film',
    category: 'veecut_originals',
    description: 'Modern organic celluloid emulsion with immaculate natural skin tones, smooth highlight rolloff, and gentle matte black floor.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.95,
    popularityScore: 96,
    usageCount: 410000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'clean', 'film', 'organic', 'skin', 'natural'],
    previewGradient: 'linear-gradient(135deg, #334155 0%, #64748b 40%, #f1f5f9 80%, #cbd5e1 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 6,
      tint: -2,
      contrast: 1.12,
      saturation: 1.05,
      highlights: -12,
      shadows: 8,
      whites: -4,
      fade: 10,
      grain: 16,
      sharpen: 10,
      wheels: {
        lift: { r: 0.02, g: 0.01, b: 0.02, y: 0.03 },
        gamma: { r: 0.02, g: 0.01, b: -0.01, y: 0.0 },
        gain: { r: 0.04, g: 0.03, b: 0.01, y: 0.02 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_soft_portrait',
    name: 'Soft Portrait',
    category: 'veecut_originals',
    description: 'Flattering beauty and portrait grade with gentle midtone diffusion, protected skin luminance, and subtle peach blossom warmth.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.93,
    popularityScore: 95,
    usageCount: 365000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'soft', 'portrait', 'beauty', 'glow', 'skin'],
    previewGradient: 'linear-gradient(135deg, #fda4af 0%, #f43f5e 40%, #fecdd3 80%, #fff1f2 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 14,
      tint: -8,
      contrast: 1.06,
      saturation: 1.08,
      brilliance: 18,
      highlights: -20,
      shadows: 14,
      clarity: -12,
      sharpen: 14,
      vignette: 0.15,
      wheels: {
        lift: { r: 0.05, g: 0.02, b: 0.02, y: 0.02 },
        gamma: { r: 0.06, g: 0.02, b: -0.02, y: 0.02 },
        gain: { r: 0.12, g: 0.06, b: 0.02, y: 0.04 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_moody',
    name: 'Moody',
    category: 'veecut_originals',
    description: 'Atmospheric Nordic twilight aesthetic with desaturated earth tones, misty shadow fog, and deep evocative contrast.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.92,
    popularityScore: 94,
    usageCount: 350000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'moody', 'twilight', 'dark', 'fog', 'nordic'],
    previewGradient: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 40%, #4338ca 80%, #6366f1 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -18,
      tint: 15,
      contrast: 1.30,
      saturation: 0.82,
      highlights: -15,
      shadows: 10,
      blacks: -12,
      fade: 16,
      grain: 24,
      vignette: 0.32,
      wheels: {
        lift: { r: -0.08, g: -0.02, b: 0.14, y: -0.02 },
        gamma: { r: -0.04, g: -0.02, b: 0.06, y: 0.0 },
        gain: { r: 0.02, g: 0.04, b: 0.12, y: 0.02 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_vintage_film',
    name: 'Vintage Film',
    category: 'veecut_originals',
    description: 'Authentic 1970s analog print reproduction with warm faded shadows, rich sepia undertones, and prominent organic 35mm grain.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.91,
    popularityScore: 93,
    usageCount: 340000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'vintage', 'film', '1970s', 'analog', 'sepia', 'grain'],
    previewGradient: 'linear-gradient(135deg, #451a03 0%, #78350f 40%, #d97706 80%, #fde68a 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 36,
      tint: 18,
      contrast: 1.15,
      saturation: 1.18,
      highlights: -22,
      shadows: 20,
      fade: 22,
      grain: 45,
      vignette: 0.38,
      wheels: {
        lift: { r: 0.12, g: 0.08, b: -0.05, y: 0.06 },
        gamma: { r: 0.10, g: 0.05, b: -0.08, y: 0.02 },
        gain: { r: 0.20, g: 0.10, b: -0.10, y: 0.04 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_cold_cinema',
    name: 'Cold Cinema',
    category: 'veecut_originals',
    description: 'Chilling arctic thriller look featuring steel cyan shadow washes, crisp frosty highlights, and high micro-contrast edge definition.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.93,
    popularityScore: 92,
    usageCount: 310000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'cold', 'cinema', 'arctic', 'cyan', 'thriller'],
    previewGradient: 'linear-gradient(135deg, #082f49 0%, #0369a1 40%, #38bdf8 80%, #e0f2fe 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -35,
      tint: -15,
      contrast: 1.34,
      saturation: 0.88,
      clarity: 20,
      sharpen: 18,
      highlights: 12,
      shadows: -18,
      vignette: 0.25,
      grain: 14,
      wheels: {
        lift: { r: -0.15, g: 0.02, b: 0.20, y: -0.04 },
        gamma: { r: -0.08, g: 0.02, b: 0.10, y: 0.0 },
        gain: { r: -0.02, g: 0.05, b: 0.18, y: 0.05 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'veecut_warm_film',
    name: 'Warm Film',
    category: 'veecut_originals',
    description: 'Sun-drenched golden hour Kodachrome nostalgia with warm radiant skin tones, soft matte shadows, and golden amber vignette.',
    author: 'VeeCut Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.95,
    popularityScore: 96,
    usageCount: 420000,
    isTrending: true,
    isOriginal: true,
    tags: ['veecut', 'signature', 'warm', 'film', 'kodachrome', 'golden-hour', 'nostalgia'],
    previewGradient: 'linear-gradient(135deg, #9a3412 0%, #ea580c 40%, #fb923c 80%, #ffedd5 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 40,
      tint: -6,
      contrast: 1.20,
      saturation: 1.22,
      brilliance: 22,
      highlights: -14,
      shadows: 16,
      fade: 12,
      grain: 28,
      vignette: 0.26,
      wheels: {
        lift: { r: 0.10, g: 0.04, b: -0.06, y: 0.02 },
        gamma: { r: 0.14, g: 0.06, b: -0.08, y: 0.03 },
        gain: { r: 0.25, g: 0.12, b: -0.14, y: 0.06 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-01T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 1. TRAVEL CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'trv_santorini_blue',
    name: 'Santorini Azure Sky',
    category: 'travel',
    description: 'Ultra-clear Mediterranean sky saturation, boosted cyan/blue tones, and crisp white limestone contrast.',
    author: 'VeeCut Travel Team',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.92,
    popularityScore: 94,
    usageCount: 210000,
    tags: ['travel', 'santorini', 'blue', 'sky', 'mediterranean', 'sea', 'summer'],
    previewGradient: 'linear-gradient(135deg, #0284c7 0%, #38bdf8 50%, #ffffff 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -8,
      tint: -6,
      contrast: 1.24,
      saturation: 1.32,
      vibrance: 25,
      highlights: -8,
      shadows: 12,
      clarity: 18,
      sharpen: 15,
      hsl: {
        red: createDefaultHslBand(0),
        orange: createDefaultHslBand(30),
        yellow: createDefaultHslBand(60),
        green: { ...createDefaultHslBand(120), hue: -5, saturation: 15, luminance: 5 },
        cyan: { ...createDefaultHslBand(180), hue: 5, saturation: 35, luminance: 10 },
        blue: { ...createDefaultHslBand(240), hue: 0, saturation: 40, luminance: -5 },
        purple: createDefaultHslBand(280),
        magenta: createDefaultHslBand(320),
      },
    },
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'trv_bali_sunset',
    name: 'Bali Golden Sunset',
    category: 'travel',
    description: 'Rich tropical sunset hues with burning orange skies, vibrant palm greens, and golden water reflections.',
    author: 'VeeCut Travel Team',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.90,
    popularityScore: 91,
    usageCount: 185000,
    tags: ['travel', 'bali', 'sunset', 'tropical', 'warm', 'ocean'],
    previewGradient: 'linear-gradient(135deg, #c2410c 0%, #ea580c 40%, #facc15 80%, #15803d 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 38,
      tint: 14,
      contrast: 1.22,
      saturation: 1.28,
      highlights: -16,
      shadows: 18,
      vignette: 0.22,
    },
    createdAt: '2025-01-16T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 2. VLOG CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'vlog_clean_studio',
    name: 'Clean Creator Studio',
    category: 'vlog',
    description: 'High-key bright aesthetic with lifted exposure, smooth flattering skin tones, and pristine neutral whites.',
    author: 'VeeCut Creator Hub',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.95,
    popularityScore: 97,
    usageCount: 380000,
    isTrending: true,
    tags: ['vlog', 'creator', 'studio', 'clean', 'bright', 'talking-head'],
    previewGradient: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #94a3b8 100%)',
    colorGrade: {
      ...baseGrade(),
      exposure: 0.25,
      contrast: 1.08,
      brightness: 5,
      saturation: 1.08,
      highlights: -15,
      shadows: 22,
      whites: 8,
      clarity: 6,
      sharpen: 12,
    },
    createdAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'vlog_cozy_coffee',
    name: 'Cozy Cafe Vlog',
    category: 'vlog',
    description: 'Gentle warm pastel tones, caramel shadows, and relaxed atmosphere for daily routine lifestyle videos.',
    author: 'VeeCut Creator Hub',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.89,
    popularityScore: 89,
    usageCount: 160000,
    tags: ['vlog', 'cozy', 'cafe', 'coffee', 'lifestyle', 'warm', 'aesthetic'],
    previewGradient: 'linear-gradient(135deg, #713f12 0%, #a16207 50%, #fef08a 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 22,
      tint: 4,
      contrast: 1.10,
      saturation: 1.05,
      fade: 14,
      highlights: -18,
      shadows: 14,
      grain: 12,
    },
    createdAt: '2025-01-19T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 3. SPORTS CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'sprt_dynamic_action',
    name: 'Dynamic Action HDR',
    category: 'sports',
    description: 'Extreme micro-contrast, punchy saturated colors, and crisp edge sharpening designed for fast action footage.',
    author: 'VeeCut Sports Lab',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.93,
    popularityScore: 95,
    usageCount: 275000,
    isTrending: true,
    tags: ['sports', 'action', 'hdr', 'dynamic', 'fitness', 'speed', 'extreme'],
    previewGradient: 'linear-gradient(135deg, #b91c1c 0%, #ea580c 50%, #facc15 100%)',
    colorGrade: {
      ...baseGrade(),
      contrast: 1.35,
      saturation: 1.30,
      clarity: 28,
      sharpen: 32,
      highlights: 10,
      shadows: -15,
      blacks: -10,
      vibrance: 20,
    },
    createdAt: '2025-01-20T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 4. GAMING CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'game_cyber_synthwave',
    name: 'Cyber Synthwave Neon',
    category: 'gaming',
    description: 'Deep abyssal black level with hyper-vivid magenta and cyan neon glow for gameplay highlights and stream clips.',
    author: 'VeeCut Esports Lab',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.96,
    popularityScore: 98,
    usageCount: 410000,
    isTrending: true,
    tags: ['gaming', 'cyberpunk', 'synthwave', 'neon', 'magenta', 'cyan', 'esports', 'twitch'],
    previewGradient: 'linear-gradient(135deg, #020617 0%, #c026d3 50%, #06b6d4 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -12,
      tint: 35,
      contrast: 1.42,
      saturation: 1.38,
      blacks: -20,
      shadows: -18,
      highlights: 22,
      clarity: 22,
      vignette: 0.35,
      wheels: {
        lift: { r: -0.15, g: -0.05, b: 0.20, y: -0.10 },
        gamma: { r: 0.15, g: -0.05, b: 0.12, y: 0.02 },
        gain: { r: 0.20, g: -0.02, b: 0.25, y: 0.08 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-22T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 5. SOCIAL & REELS CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'soc_viral_hook',
    name: 'Viral Hook Boost',
    category: 'social',
    description: 'High-energy vibrancy with radiant skin tones, optimized for stopping scrollers on Reels, Shorts, and TikTok.',
    author: 'VeeCut Social Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.97,
    popularityScore: 99,
    usageCount: 560000,
    isTrending: true,
    tags: ['social', 'reels', 'shorts', 'tiktok', 'viral', 'hook', 'punchy'],
    previewGradient: 'linear-gradient(135deg, #f43f5e 0%, #fb923c 50%, #38bdf8 100%)',
    colorGrade: {
      ...baseGrade(),
      exposure: 0.18,
      contrast: 1.25,
      saturation: 1.28,
      vibrance: 26,
      brilliance: 20,
      highlights: -12,
      shadows: 16,
      clarity: 15,
      sharpen: 18,
    },
    createdAt: '2025-01-25T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 6. NEW CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'new_tokyo_night_drive',
    name: 'Tokyo Night Drive',
    category: 'new',
    description: 'Fresh cinematic nocturnal grade featuring damp asphalt reflections, magenta signs, and cyan streetlamps.',
    author: 'VeeCut Color Studio',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.94,
    popularityScore: 92,
    usageCount: 95000,
    isNew: true,
    isTrending: true,
    tags: ['new', 'tokyo', 'night', 'rain', 'drive', 'neon', 'cinematic'],
    previewGradient: 'linear-gradient(135deg, #09090b 0%, #4c1d95 50%, #06b6d4 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -22,
      tint: 28,
      contrast: 1.36,
      saturation: 1.24,
      blacks: -12,
      shadows: -10,
      highlights: 18,
      vignette: 0.32,
      grain: 20,
    },
    createdAt: '2025-02-01T00:00:00Z',
  },
  // -------------------------------------------------------------------------
  // 7. CINEMATIC CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'cin_teal_orange',
    name: 'Blockbuster Teal & Orange',
    category: 'cinematic',
    description: 'Iconic Hollywood action color separation with teal shadows and warm amber skin highlights.',
    author: 'VeeCut Color Studio',
    version: '2.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.95,
    popularityScore: 99,
    usageCount: 248000,
    isTrending: true,
    tags: ['hollywood', 'teal', 'orange', 'action', 'blockbuster', 'widescreen'],
    previewGradient: 'linear-gradient(135deg, #0d9488 0%, #0369a1 40%, #f59e0b 80%, #d97706 100%)',
    lutId: 'teal-orange',
    colorGrade: {
      ...baseGrade(),
      temperature: 18,
      tint: -12,
      contrast: 1.28,
      saturation: 1.25,
      highlights: -10,
      shadows: 14,
      vignette: 0.28,
      lutIntensity: 0.9,
      wheels: {
        lift: { r: -0.15, g: 0.05, b: 0.18, y: -0.05 },
        gamma: { r: 0.05, g: -0.02, b: -0.05, y: 0.0 },
        gain: { r: 0.18, g: 0.08, b: -0.12, y: 0.08 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    effects: [
      {
        id: 'fx_cin_vignette_1',
        effectId: 'lumina.vignette',
        name: 'Anamorphic Edge Vignette',
        enabled: true,
        opacity: 0.5,
        params: { amount: 0.35, radius: 0.82, softness: 0.75, color: '#000000' },
      },
    ],
    createdAt: '2025-01-10T12:00:00Z',
  },
  {
    id: 'cin_matrix_green',
    name: 'Matrix Cyber Code',
    category: 'cinematic',
    description: 'Stylized emerald-tinted dystopian tone with crushed blacks and luminous green midtones.',
    author: 'VeeCut Sci-Fi Lab',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.88,
    popularityScore: 92,
    usageCount: 142000,
    tags: ['matrix', 'cyberpunk', 'green', 'sci-fi', 'dystopian'],
    previewGradient: 'linear-gradient(135deg, #064e3b 0%, #047857 40%, #10b981 80%, #052e16 100%)',
    lutId: 'matrix-green',
    colorGrade: {
      ...baseGrade(),
      temperature: -14,
      tint: -38,
      contrast: 1.35,
      saturation: 1.15,
      shadows: -15,
      highlights: 10,
      vignette: 0.35,
      wheels: {
        lift: { r: -0.1, g: 0.15, b: -0.1, y: -0.08 },
        gamma: { r: -0.05, g: 0.22, b: -0.08, y: 0.02 },
        gain: { r: 0.05, g: 0.25, b: 0.02, y: 0.05 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-12T12:00:00Z',
  },
  {
    id: 'cin_dune_sandstorm',
    name: 'Dune Desert Amber',
    category: 'cinematic',
    description: 'Warm arid ochre and sun-scorched copper palette inspired by epic desert sci-fi cinematography.',
    author: 'VeeCut Color Studio',
    version: '1.5',
    scope: 'color',
    intensity: 1.0,
    rating: 4.92,
    popularityScore: 95,
    usageCount: 189000,
    isTrending: true,
    tags: ['dune', 'desert', 'amber', 'sandstorm', 'epic', 'warm'],
    previewGradient: 'linear-gradient(135deg, #78350f 0%, #b45309 40%, #f59e0b 80%, #fcd34d 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 42,
      tint: 16,
      contrast: 1.22,
      saturation: 1.18,
      highlights: -12,
      shadows: 20,
      vignette: 0.24,
      fade: 8,
      wheels: {
        lift: { r: 0.18, g: 0.08, b: -0.12, y: 0.02 },
        gamma: { r: 0.22, g: 0.12, b: -0.15, y: 0.04 },
        gain: { r: 0.28, g: 0.18, b: -0.08, y: 0.1 },
        offset: { r: 0.05, g: 0.02, b: -0.05, y: 0 },
      },
    },
    createdAt: '2025-01-15T12:00:00Z',
  },
  {
    id: 'cin_interstellar_space',
    name: 'Interstellar Deep Space',
    category: 'cinematic',
    description: 'Ultra-deep blacks, celestial starlight contrast, and pristine cold cosmic shadows.',
    author: 'VeeCut Color Studio',
    version: '1.1',
    scope: 'color',
    intensity: 1.0,
    rating: 4.9,
    popularityScore: 91,
    usageCount: 135000,
    tags: ['space', 'cosmic', 'deep black', 'interstellar', 'cold'],
    previewGradient: 'linear-gradient(135deg, #020617 0%, #0f172a 40%, #1e293b 80%, #38bdf8 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -22,
      tint: 8,
      contrast: 1.42,
      saturation: 0.95,
      blacks: -18,
      whites: 15,
      clarity: 22,
      vignette: 0.4,
    },
    createdAt: '2025-01-18T12:00:00Z',
  },
  {
    id: 'cin_bleach_bypass',
    name: 'Bleach Bypass War Film',
    category: 'cinematic',
    description: 'Desaturated gritty silver retention look with harsh dynamic contrast and metallic textures.',
    author: 'VeeCut Master Grader',
    version: '1.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.86,
    popularityScore: 88,
    usageCount: 98000,
    tags: ['bleach bypass', 'gritty', 'war', 'action', 'metallic', 'silver'],
    previewGradient: 'linear-gradient(135deg, #3f3f46 0%, #71717a 50%, #d4d4d8 100%)',
    colorGrade: {
      ...baseGrade(),
      saturation: 0.55,
      contrast: 1.52,
      exposure: -0.08,
      highlights: 18,
      shadows: -22,
      clarity: 35,
      vignette: 0.32,
    },
    createdAt: '2025-01-20T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 2. FILM & ANALOG CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'film_kodak_portra_400',
    name: 'Kodak Portra 400 Color',
    category: 'film',
    description: 'Natural organic skin rendition, soft highlight rolloff, and creamy analog warmth.',
    author: 'Analog Film Lab',
    version: '2.1',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.98,
    popularityScore: 98,
    usageCount: 312000,
    isTrending: true,
    tags: ['kodak', 'portra', 'analog', 'film stock', 'creamy', 'skin'],
    previewGradient: 'linear-gradient(135deg, #fbbf24 0%, #f87171 40%, #fb923c 80%, #fef3c7 100%)',
    lutId: 'kodak-portra',
    colorGrade: {
      ...baseGrade(),
      temperature: 15,
      tint: 8,
      contrast: 1.08,
      saturation: 1.12,
      highlights: -16,
      shadows: 18,
      grain: 22,
      fade: 6,
    },
    effects: [
      {
        id: 'fx_grain_portra',
        effectId: 'lumina.film_grain',
        name: '35mm Fine Film Grain',
        enabled: true,
        opacity: 0.35,
        params: { intensity: 0.28, grainSize: 1, animated: true },
      },
    ],
    createdAt: '2025-01-05T12:00:00Z',
  },
  {
    id: 'film_fuji_velvia_50',
    name: 'Fujifilm Velvia 50 Vivid',
    category: 'film',
    description: 'High saturation reversal slide film with deep ocean blues, vibrant greens, and rich magenta skies.',
    author: 'Analog Film Lab',
    version: '1.4',
    scope: 'color',
    intensity: 1.0,
    rating: 4.93,
    popularityScore: 94,
    usageCount: 175000,
    tags: ['fuji', 'velvia', 'slide film', 'vivid', 'nature', 'landscape'],
    previewGradient: 'linear-gradient(135deg, #059669 0%, #2563eb 50%, #db2777 100%)',
    lutId: 'fuji-velvia',
    colorGrade: {
      ...baseGrade(),
      temperature: -8,
      tint: 14,
      contrast: 1.32,
      saturation: 1.48,
      vibrance: 25,
      highlights: 8,
      shadows: -10,
    },
    createdAt: '2025-01-08T12:00:00Z',
  },
  {
    id: 'film_cinestill_800t',
    name: 'Cinestill 800T Halation',
    category: 'film',
    description: 'Tungsten-balanced cinematic motion stock with distinctive red halation around bright streetlights.',
    author: 'VeeCut Analog Lab',
    version: '1.8',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.96,
    popularityScore: 97,
    usageCount: 220000,
    isTrending: true,
    tags: ['cinestill', '800t', 'halation', 'night', 'tungsten', 'neon'],
    previewGradient: 'linear-gradient(135deg, #0369a1 0%, #1e1b4b 50%, #ef4444 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -28,
      tint: 22,
      contrast: 1.26,
      saturation: 1.25,
      shadows: 14,
      vignette: 0.25,
      grain: 28,
    },
    effects: [
      {
        id: 'fx_cinestill_glow',
        effectId: 'lumina.glow',
        name: 'Red Halation Bloom',
        enabled: true,
        opacity: 0.6,
        params: { intensity: 1.2, radius: 24, threshold: 0.45, colorTint: '#ff3344' },
      },
    ],
    createdAt: '2025-01-14T12:00:00Z',
  },
  {
    id: 'film_super8_warm',
    name: 'Super 8mm Home Movie',
    category: 'film',
    description: 'Nostalgic 1960s 8mm celluloid texture with warm sun flares, soft frame jitter, and organic grain.',
    author: 'VeeCut Retro Lab',
    version: '1.3',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.89,
    popularityScore: 89,
    usageCount: 115000,
    tags: ['super 8', 'vintage', 'home movie', 'nostalgia', 'grain', 'warm'],
    previewGradient: 'linear-gradient(135deg, #b45309 0%, #d97706 40%, #fde68a 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 38,
      tint: 18,
      contrast: 0.92,
      saturation: 0.95,
      fade: 18,
      vignette: 0.42,
      grain: 45,
    },
    effects: [
      {
        id: 'fx_super8_grain',
        effectId: 'lumina.film_grain',
        name: 'Super 8 Heavy Grain',
        enabled: true,
        opacity: 0.65,
        params: { intensity: 0.55, grainSize: 2, animated: true },
      },
    ],
    createdAt: '2025-01-19T12:00:00Z',
  },
  {
    id: 'film_technicolor_3strip',
    name: 'Technicolor 3-Strip Classic',
    category: 'film',
    description: 'Golden Age Hollywood saturated dyes with radiant primary reds, deep cyan skies, and yellow gold.',
    author: 'VeeCut Vintage Masters',
    version: '1.1',
    scope: 'color',
    intensity: 1.0,
    rating: 4.87,
    popularityScore: 86,
    usageCount: 88000,
    tags: ['technicolor', 'golden age', 'hollywood', 'classic', 'primary colors'],
    previewGradient: 'linear-gradient(135deg, #dc2626 0%, #2563eb 50%, #facc15 100%)',
    colorGrade: {
      ...baseGrade(),
      saturation: 1.45,
      contrast: 1.25,
      vibrance: 30,
      highlights: 5,
      shadows: 8,
    },
    createdAt: '2025-01-22T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 3. VINTAGE & RETRO CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'vint_kodachrome_70s',
    name: '1970s Kodachrome Warmth',
    category: 'vintage',
    description: 'Warm golden hues, gentle contrast, and nostalgic retro vacation colors.',
    author: 'Retro Archives',
    version: '2.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.94,
    popularityScore: 96,
    usageCount: 260000,
    isTrending: true,
    tags: ['70s', 'kodachrome', 'vintage', 'warm', 'retro', 'sunlit'],
    previewGradient: 'linear-gradient(135deg, #d97706 0%, #f59e0b 50%, #fed7aa 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 34,
      tint: 14,
      contrast: 0.96,
      saturation: 0.9,
      brightness: 0.04,
      fade: 12,
      vignette: 0.22,
      grain: 25,
    },
    createdAt: '2025-01-04T12:00:00Z',
  },
  {
    id: 'vint_synthwave_80s',
    name: '1980s Synthwave Neon Glow',
    category: 'vintage',
    description: 'Retro arcade synthwave purple twilight with bright magenta and cyan laser highlights.',
    author: 'VeeCut Cyber Team',
    version: '1.6',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.91,
    popularityScore: 93,
    usageCount: 154000,
    tags: ['80s', 'synthwave', 'neon', 'retro', 'arcade', 'purple'],
    previewGradient: 'linear-gradient(135deg, #581c87 0%, #c026d3 50%, #06b6d4 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -24,
      tint: 44,
      contrast: 1.38,
      saturation: 1.45,
      vignette: 0.35,
    },
    effects: [
      {
        id: 'fx_synth_chroma',
        effectId: 'lumina.chromatic_aberration',
        name: 'RGB Separation Twitch',
        enabled: true,
        opacity: 0.5,
        params: { offset: 10, angle: 90 },
      },
    ],
    createdAt: '2025-01-09T12:00:00Z',
  },
  {
    id: 'vint_vhs_camcorder_90s',
    name: '1990s VHS Camcorder',
    category: 'vintage',
    description: 'Authentic 90s handheld camcorder color bleed, tracking static, and magnetic tape warmth.',
    author: 'VeeCut Glitch Lab',
    version: '1.4',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.92,
    popularityScore: 94,
    usageCount: 188000,
    isTrending: true,
    tags: ['90s', 'vhs', 'camcorder', 'tracking', 'glitch', 'retro tape'],
    previewGradient: 'linear-gradient(135deg, #1e293b 0%, #475569 40%, #0284c7 80%, #ef4444 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 12,
      tint: -10,
      contrast: 1.15,
      saturation: 1.1,
      sharpen: 30,
      grain: 40,
    },
    effects: [
      {
        id: 'fx_vhs_tape',
        effectId: 'lumina.vhs',
        name: 'VHS Tape Degradation',
        enabled: true,
        opacity: 0.65,
        params: { trackingNoise: 0.45, colorBleed: 0.55 },
      },
    ],
    createdAt: '2025-01-16T12:00:00Z',
  },
  {
    id: 'vint_polaroid_600',
    name: 'Instant Polaroid 600',
    category: 'vintage',
    description: 'Dreamy faded instant film look with creamy cyan highlights and lifted pastel shadows.',
    author: 'Instant Photo Collective',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.88,
    popularityScore: 89,
    usageCount: 110000,
    tags: ['polaroid', 'instant film', 'pastel', 'faded', 'nostalgic'],
    previewGradient: 'linear-gradient(135deg, #0284c7 0%, #38bdf8 40%, #fef08a 80%, #f43f5e 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -10,
      tint: 12,
      contrast: 0.9,
      saturation: 0.88,
      fade: 24,
      shadows: 22,
      vignette: 0.28,
    },
    createdAt: '2025-01-21T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 4. PORTRAIT & SKIN TONE CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'port_golden_hour_glow',
    name: 'Golden Hour Sunset Glow',
    category: 'portrait',
    description: 'Radiant amber warmth, smoothed skin tone contrast, and golden backlighting radiance.',
    author: 'VeeCut Portrait Studio',
    version: '2.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.97,
    popularityScore: 99,
    usageCount: 380000,
    isTrending: true,
    tags: ['golden hour', 'sunset', 'portrait', 'skin glow', 'warm', 'beauty'],
    previewGradient: 'linear-gradient(135deg, #f59e0b 0%, #f97316 40%, #ec4899 80%, #fef08a 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 36,
      tint: 12,
      contrast: 1.06,
      saturation: 1.18,
      highlights: -18,
      shadows: 16,
      vibrance: 15,
      vignette: 0.18,
    },
    createdAt: '2025-01-02T12:00:00Z',
  },
  {
    id: 'port_clean_porcelain',
    name: 'Clean Porcelain Studio',
    category: 'portrait',
    description: 'Bright clean beauty lighting with silky smooth skin tones, reduced redness, and luminous whites.',
    author: 'VeeCut Beauty Lab',
    version: '1.5',
    scope: 'color',
    intensity: 1.0,
    rating: 4.91,
    popularityScore: 92,
    usageCount: 165000,
    tags: ['porcelain', 'clean', 'beauty', 'studio', 'commercial', 'smooth'],
    previewGradient: 'linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 40%, #cbd5e1 80%, #fce7f3 100%)',
    colorGrade: {
      ...baseGrade(),
      exposure: 0.12,
      temperature: -4,
      tint: -6,
      contrast: 1.04,
      saturation: 1.05,
      whites: 12,
      highlights: -10,
      shadows: 10,
      clarity: -8, // soft beauty
    },
    createdAt: '2025-01-11T12:00:00Z',
  },
  {
    id: 'port_rosy_radiance',
    name: 'Rosy Velvet Radiance',
    category: 'portrait',
    description: 'Subtle blush pink undertones, creamy midtones, and gentle atmospheric highlight diffusion.',
    author: 'VeeCut Portrait Studio',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.89,
    popularityScore: 90,
    usageCount: 128000,
    tags: ['rosy', 'velvet', 'blush', 'glow', 'editorial', 'fashion'],
    previewGradient: 'linear-gradient(135deg, #fda4af 0%, #fb7185 50%, #f43f5e 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 10,
      tint: 24,
      contrast: 1.02,
      saturation: 1.12,
      highlights: -14,
      shadows: 14,
      fade: 10,
    },
    createdAt: '2025-01-17T12:00:00Z',
  },
  {
    id: 'port_matte_editorial',
    name: 'Matte Editorial Vogue',
    category: 'portrait',
    description: 'High-fashion magazine matte finish with crushed deep shadows and neutral skin contrast.',
    author: 'Editorial Grader',
    version: '1.3',
    scope: 'color',
    intensity: 1.0,
    rating: 4.92,
    popularityScore: 93,
    usageCount: 147000,
    tags: ['editorial', 'vogue', 'fashion', 'matte', 'high fashion'],
    previewGradient: 'linear-gradient(135deg, #18181b 0%, #3f3f46 50%, #a1a1aa 100%)',
    colorGrade: {
      ...baseGrade(),
      contrast: 1.22,
      saturation: 0.92,
      fade: 18,
      shadows: 12,
      highlights: -8,
      blacks: 14,
      vignette: 0.22,
    },
    createdAt: '2025-01-23T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 5. LANDSCAPE & NATURE CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'land_emerald_forest',
    name: 'Lush Emerald Forest',
    category: 'landscape',
    description: 'Deep verdant moss greens, rich forest foliage saturation, and crisp misty atmospheric depth.',
    author: 'Nature Explorers',
    version: '1.6',
    scope: 'color',
    intensity: 1.0,
    rating: 4.93,
    popularityScore: 95,
    usageCount: 198000,
    tags: ['forest', 'emerald', 'nature', 'landscape', 'foliage', 'green'],
    previewGradient: 'linear-gradient(135deg, #064e3b 0%, #059669 40%, #10b981 80%, #a7f3d0 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -12,
      tint: -22,
      contrast: 1.25,
      saturation: 1.35,
      vibrance: 28,
      shadows: 8,
      clarity: 18,
      vignette: 0.2,
    },
    createdAt: '2025-01-03T12:00:00Z',
  },
  {
    id: 'land_alpine_blue',
    name: 'Alpine Mountain Glacier',
    category: 'landscape',
    description: 'Crystalline turquoise glacial waters, sharp granite mountain peaks, and crisp polar skies.',
    author: 'Alpine Visuals',
    version: '1.4',
    scope: 'color',
    intensity: 1.0,
    rating: 4.9,
    popularityScore: 91,
    usageCount: 132000,
    tags: ['alpine', 'glacier', 'mountain', 'blue', 'crisp', 'polar'],
    previewGradient: 'linear-gradient(135deg, #0284c7 0%, #0ea5e9 40%, #38bdf8 80%, #e0f2fe 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -26,
      tint: 4,
      contrast: 1.3,
      saturation: 1.2,
      whites: 15,
      clarity: 30,
      sharpen: 25,
    },
    createdAt: '2025-01-13T12:00:00Z',
  },
  {
    id: 'land_autumn_amber',
    name: 'Autumn Amber Foliage',
    category: 'landscape',
    description: 'Fiery crimson maples, warm golden birch leaves, and rustic pumpkin patch glow.',
    author: 'Nature Explorers',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.91,
    popularityScore: 92,
    usageCount: 156000,
    tags: ['autumn', 'fall', 'foliage', 'amber', 'maple', 'warm nature'],
    previewGradient: 'linear-gradient(135deg, #991b1b 0%, #ea580c 40%, #f59e0b 80%, #fef3c7 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 38,
      tint: 18,
      contrast: 1.18,
      saturation: 1.38,
      vibrance: 32,
      shadows: 14,
    },
    createdAt: '2025-01-24T12:00:00Z',
  },
  {
    id: 'land_ocean_sapphire',
    name: 'Deep Ocean Sapphire',
    category: 'landscape',
    description: 'Aquamarine coral shallows, deep cobalt oceanic trenches, and sun-drenched coastal spray.',
    author: 'Oceanic Media',
    version: '1.3',
    scope: 'color',
    intensity: 1.0,
    rating: 4.88,
    popularityScore: 88,
    usageCount: 104000,
    tags: ['ocean', 'sea', 'sapphire', 'coast', 'water', 'tropical'],
    previewGradient: 'linear-gradient(135deg, #0c4a6e 0%, #0284c7 40%, #06b6d4 80%, #ccfbf1 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -18,
      tint: -14,
      contrast: 1.22,
      saturation: 1.32,
      vibrance: 20,
      highlights: -10,
    },
    createdAt: '2025-01-26T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 6. BLACK & WHITE / NOIR CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'bw_silver_gelatin',
    name: 'Silver Gelatin Fine Art',
    category: 'black_white',
    description: 'Fine art darkroom archival print with continuous tonal gradation and silvery highlight sheen.',
    author: 'Fine Art Printmaker',
    version: '2.0',
    scope: 'color',
    intensity: 1.0,
    rating: 4.96,
    popularityScore: 97,
    usageCount: 215000,
    isTrending: true,
    tags: ['black and white', 'silver gelatin', 'monochrome', 'fine art', 'darkroom'],
    previewGradient: 'linear-gradient(135deg, #18181b 0%, #52525b 50%, #e4e4e7 100%)',
    lutId: 'noir-bnw',
    colorGrade: {
      ...baseGrade(),
      saturation: 0,
      vibrance: -100,
      contrast: 1.38,
      exposure: 0.05,
      highlights: -12,
      shadows: 18,
      whites: 10,
      blacks: -10,
      vignette: 0.28,
      grain: 20,
    },
    createdAt: '2025-01-06T12:00:00Z',
  },
  {
    id: 'bw_film_noir_crime',
    name: 'Hard Contrast Film Noir',
    category: 'black_white',
    description: 'Venetian blind shadow slits, stark high-key highlights, and ruthless crushed black drama.',
    author: 'VeeCut Cinema Lab',
    version: '1.5',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.93,
    popularityScore: 94,
    usageCount: 168000,
    tags: ['noir', 'crime', 'shadow', 'high contrast', 'hard light', 'detective'],
    previewGradient: 'linear-gradient(135deg, #000000 0%, #27272a 50%, #ffffff 100%)',
    colorGrade: {
      ...baseGrade(),
      saturation: 0,
      contrast: 1.65,
      exposure: -0.15,
      shadows: -35,
      highlights: 25,
      whites: 20,
      blacks: -30,
      vignette: 0.55,
      grain: 35,
    },
    effects: [
      {
        id: 'fx_noir_vignette',
        effectId: 'lumina.vignette',
        name: 'Heavy Noir Vignette',
        enabled: true,
        opacity: 0.75,
        params: { amount: 0.6, radius: 0.7, softness: 0.5, color: '#000000' },
      },
    ],
    createdAt: '2025-01-15T12:00:00Z',
  },
  {
    id: 'bw_infrared_dream',
    name: 'Infrared Surreal Monochrome',
    category: 'black_white',
    description: 'Simulated 720nm infrared spectrum with luminous white tree foliage and pitch-black skies.',
    author: 'VeeCut Experimental',
    version: '1.1',
    scope: 'color',
    intensity: 1.0,
    rating: 4.85,
    popularityScore: 84,
    usageCount: 72000,
    tags: ['infrared', 'surreal', 'monochrome', 'dreamy', 'landscape bw'],
    previewGradient: 'linear-gradient(135deg, #09090b 0%, #71717a 60%, #fafafa 100%)',
    colorGrade: {
      ...baseGrade(),
      saturation: 0,
      contrast: 1.45,
      exposure: 0.2,
      whites: 35,
      highlights: 30,
      shadows: -20,
      clarity: -10,
    },
    createdAt: '2025-01-27T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 7. URBAN & STREET CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'urb_cyberpunk_tokyo',
    name: 'Cyberpunk Neo-Tokyo',
    category: 'urban',
    description: 'Electric neon magenta billboards, cobalt wet asphalt reflections, and high-energy city contrast.',
    author: 'VeeCut Cyber Team',
    version: '2.2',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.97,
    popularityScore: 99,
    usageCount: 340000,
    isTrending: true,
    tags: ['cyberpunk', 'tokyo', 'neon', 'magenta', 'cyan', 'city', 'night street'],
    previewGradient: 'linear-gradient(135deg, #0891b2 0%, #4f46e5 40%, #c026d3 80%, #f43f5e 100%)',
    lutId: 'cyberpunk',
    colorGrade: {
      ...baseGrade(),
      temperature: -30,
      tint: 48,
      contrast: 1.4,
      saturation: 1.5,
      vibrance: 35,
      highlights: 12,
      shadows: 18,
      vignette: 0.35,
    },
    effects: [
      {
        id: 'fx_cyber_glow',
        effectId: 'lumina.glow',
        name: 'Cyber Neon Bloom',
        enabled: true,
        opacity: 0.65,
        params: { intensity: 1.3, radius: 26, threshold: 0.35, colorTint: '#00f0ff' },
      },
      {
        id: 'fx_cyber_chroma',
        effectId: 'lumina.chromatic_aberration',
        name: 'RGB Edge Glitch',
        enabled: true,
        opacity: 0.45,
        params: { offset: 12, angle: 45 },
      },
    ],
    createdAt: '2025-01-01T12:00:00Z',
  },
  {
    id: 'urb_metro_steel_glass',
    name: 'Metro Steel & Architecture',
    category: 'urban',
    description: 'Minimalist metallic gray skyscrapers, desaturated street elements, and sharp crisp reflections.',
    author: 'Urban Architectural Lab',
    version: '1.3',
    scope: 'color',
    intensity: 1.0,
    rating: 4.88,
    popularityScore: 89,
    usageCount: 112000,
    tags: ['architecture', 'steel', 'glass', 'metro', 'skyscraper', 'urban'],
    previewGradient: 'linear-gradient(135deg, #334155 0%, #64748b 50%, #cbd5e1 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -14,
      tint: -8,
      contrast: 1.28,
      saturation: 0.72,
      clarity: 32,
      sharpen: 30,
      whites: 12,
    },
    createdAt: '2025-01-18T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 8. MOODY & ATMOSPHERIC CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'mood_teal_solitude',
    name: 'Moody Teal Solitude',
    category: 'mood',
    description: 'Melancholy deep teal shadows, muted highlights, and cinematic emotional introspection.',
    author: 'Atmospheric Arts',
    version: '1.7',
    scope: 'color',
    intensity: 1.0,
    rating: 4.94,
    popularityScore: 96,
    usageCount: 235000,
    isTrending: true,
    tags: ['moody', 'teal', 'solitude', 'melancholy', 'cinematic', 'emotional'],
    previewGradient: 'linear-gradient(135deg, #134e4a 0%, #0f766e 40%, #115e59 80%, #042f2e 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -20,
      tint: -18,
      contrast: 1.15,
      saturation: 0.88,
      highlights: -24,
      shadows: 12,
      fade: 14,
      vignette: 0.38,
    },
    createdAt: '2025-01-07T12:00:00Z',
  },
  {
    id: 'mood_pastel_ethereal',
    name: 'Pastel Dream Haze',
    category: 'mood',
    description: 'Ethereal lavender and cotton candy pastel glow with diffused highlights and gentle contrast.',
    author: 'Dreamscape Studios',
    version: '1.4',
    scope: 'color',
    intensity: 1.0,
    rating: 4.9,
    popularityScore: 91,
    usageCount: 142000,
    tags: ['pastel', 'dreamy', 'ethereal', 'lavender', 'cotton candy', 'soft'],
    previewGradient: 'linear-gradient(135deg, #c084fc 0%, #f472b6 40%, #fb7185 80%, #fef08a 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 8,
      tint: 28,
      contrast: 0.88,
      saturation: 1.15,
      highlights: -18,
      shadows: 26,
      fade: 20,
      exposure: 0.1,
    },
    createdAt: '2025-01-14T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 9. FOOD & LIFESTYLE CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'life_warm_bistro',
    name: 'Warm Bistro Coffee & Roast',
    category: 'lifestyle',
    description: 'Rich espresso darks, golden crust highlights, and appetizing culinary warmth.',
    author: 'Culinary Visuals',
    version: '1.5',
    scope: 'color',
    intensity: 1.0,
    rating: 4.92,
    popularityScore: 93,
    usageCount: 172000,
    isTrending: true,
    tags: ['food', 'bistro', 'coffee', 'cafe', 'warm', 'lifestyle', 'brunch'],
    previewGradient: 'linear-gradient(135deg, #78350f 0%, #b45309 40%, #f59e0b 80%, #fef3c7 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 32,
      tint: 14,
      contrast: 1.18,
      saturation: 1.32,
      vibrance: 20,
      highlights: -10,
      shadows: 14,
      clarity: 15,
    },
    createdAt: '2025-01-09T12:00:00Z',
  },
  {
    id: 'life_fresh_organic',
    name: 'Fresh Organic Market',
    category: 'lifestyle',
    description: 'Clean crisp daylight, saturated fresh produce greens and reds, and bright commercial clarity.',
    author: 'Culinary Visuals',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.87,
    popularityScore: 87,
    usageCount: 95000,
    tags: ['organic', 'fresh', 'market', 'produce', 'clean daylight', 'health'],
    previewGradient: 'linear-gradient(135deg, #65a30d 0%, #84cc16 40%, #ef4444 80%, #ffffff 100%)',
    colorGrade: {
      ...baseGrade(),
      exposure: 0.15,
      contrast: 1.12,
      saturation: 1.3,
      vibrance: 25,
      whites: 14,
      clarity: 20,
    },
    createdAt: '2025-01-20T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 10. NIGHT & LOW LIGHT CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'night_sodium_vapor',
    name: 'Sodium Vapor Streetlamp',
    category: 'night',
    description: 'Moody amber street illumination cutting through deep indigo night shadows.',
    author: 'VeeCut Night Lab',
    version: '1.3',
    scope: 'color',
    intensity: 1.0,
    rating: 4.91,
    popularityScore: 92,
    usageCount: 139000,
    tags: ['night', 'street', 'sodium vapor', 'amber', 'indigo', 'low light'],
    previewGradient: 'linear-gradient(135deg, #020617 0%, #1e1b4b 40%, #d97706 80%, #fef08a 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 18,
      tint: 28,
      contrast: 1.35,
      saturation: 1.25,
      shadows: 18,
      highlights: -12,
      vignette: 0.42,
    },
    createdAt: '2025-01-11T12:00:00Z',
  },
  {
    id: 'night_midnight_blue',
    name: 'Midnight Starlight Azure',
    category: 'night',
    description: 'Deep royal blue midnight skies, bright moonlight reflections, and celestial coolness.',
    author: 'VeeCut Night Lab',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.89,
    popularityScore: 89,
    usageCount: 114000,
    tags: ['midnight', 'night', 'starlight', 'azure', 'moonlight', 'blue'],
    previewGradient: 'linear-gradient(135deg, #020617 0%, #0369a1 50%, #38bdf8 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: -34,
      tint: 8,
      contrast: 1.3,
      saturation: 1.15,
      highlights: 10,
      shadows: -15,
      vignette: 0.35,
    },
    createdAt: '2025-01-22T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 11. CLEAN & MINIMAL CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'min_nordic_white',
    name: 'Nordic Pure Studio',
    category: 'minimal',
    description: 'Bright airy Scandinavian daylight, subtle neutral contrast, and pristine white fidelity.',
    author: 'Minimalist Studio',
    version: '1.4',
    scope: 'color',
    intensity: 1.0,
    rating: 4.93,
    popularityScore: 94,
    usageCount: 182000,
    isTrending: true,
    tags: ['nordic', 'scandinavian', 'white', 'minimal', 'clean', 'studio', 'airy'],
    previewGradient: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 40%, #e2e8f0 80%, #cbd5e1 100%)',
    colorGrade: {
      ...baseGrade(),
      exposure: 0.18,
      contrast: 0.98,
      saturation: 0.88,
      whites: 20,
      highlights: -12,
      shadows: 18,
      clarity: 8,
    },
    createdAt: '2025-01-08T12:00:00Z',
  },
  {
    id: 'min_muted_earth',
    name: 'Muted Earth Contemporary',
    category: 'minimal',
    description: 'Subdued earthy sage and terracotta accents with gentle desaturation and modern luxury calm.',
    author: 'Minimalist Studio',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.88,
    popularityScore: 88,
    usageCount: 106000,
    tags: ['muted', 'earth', 'sage', 'terracotta', 'luxury', 'contemporary'],
    previewGradient: 'linear-gradient(135deg, #57534e 0%, #78716c 40%, #a8a29e 80%, #d6d3d1 100%)',
    colorGrade: {
      ...baseGrade(),
      temperature: 8,
      tint: 4,
      contrast: 1.04,
      saturation: 0.78,
      fade: 14,
      shadows: 10,
    },
    createdAt: '2025-01-19T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 12. STYLIZED & SCI-FI CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'style_anime_pop',
    name: 'Anime Pop Vibrance',
    category: 'stylized',
    description: 'Ultra-vivid Japanese anime look with cel-shaded high-saturation pop and clear skies.',
    author: 'Anime Visual Lab',
    version: '1.5',
    scope: 'color',
    intensity: 1.0,
    rating: 4.95,
    popularityScore: 97,
    usageCount: 275000,
    isTrending: true,
    tags: ['anime', 'pop', 'cel shade', 'vivid', 'japanese animation', 'vibrant'],
    previewGradient: 'linear-gradient(135deg, #38bdf8 0%, #a855f7 40%, #ec4899 80%, #facc15 100%)',
    colorGrade: {
      ...baseGrade(),
      exposure: 0.1,
      temperature: -10,
      tint: 14,
      contrast: 1.28,
      saturation: 1.55,
      vibrance: 40,
      whites: 15,
      clarity: 25,
    },
    createdAt: '2025-01-05T12:00:00Z',
  },
  {
    id: 'style_solar_flare',
    name: 'Solar Flare Supernova',
    category: 'stylized',
    description: 'Intense golden sunburst exposure lift, lens optical dispersion, and blazing highlight power.',
    author: 'VeeCut Sci-Fi Lab',
    version: '1.1',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.86,
    popularityScore: 86,
    usageCount: 82000,
    tags: ['solar flare', 'supernova', 'sunburst', 'radiance', 'sci-fi'],
    previewGradient: 'linear-gradient(135deg, #f97316 0%, #ea580c 40%, #e11d48 80%, #fef08a 100%)',
    colorGrade: {
      ...baseGrade(),
      exposure: 0.25,
      temperature: 35,
      tint: 20,
      contrast: 1.25,
      saturation: 1.35,
      highlights: 25,
    },
    effects: [
      {
        id: 'fx_solar_glow',
        effectId: 'lumina.glow',
        name: 'Supernova Optical Bloom',
        enabled: true,
        opacity: 0.7,
        params: { intensity: 1.5, radius: 32, threshold: 0.5, colorTint: '#ffaa22' },
      },
    ],
    createdAt: '2025-01-25T12:00:00Z',
  },

  // -------------------------------------------------------------------------
  // 13. DUOTONE & POP CATEGORY
  // -------------------------------------------------------------------------
  {
    id: 'duo_red_cyan_3d',
    name: 'Anaglyph Red & Cyan 3D',
    category: 'duotone',
    description: 'Retro 3D glasses color split with crimson shadows and vibrant cyan highlights.',
    author: 'VeeCut Graphic Lab',
    version: '1.3',
    scope: 'transform_color_effects',
    intensity: 1.0,
    rating: 4.9,
    popularityScore: 90,
    usageCount: 125000,
    tags: ['duotone', 'anaglyph', '3d', 'red', 'cyan', 'graphic'],
    previewGradient: 'linear-gradient(135deg, #ef4444 0%, #dc2626 50%, #06b6d4 100%)',
    colorGrade: {
      ...baseGrade(),
      contrast: 1.4,
      saturation: 1.4,
      wheels: {
        lift: { r: 0.45, g: -0.2, b: -0.2, y: 0.0 },
        gamma: { r: 0.1, g: 0.0, b: 0.1, y: 0.0 },
        gain: { r: -0.2, g: 0.35, b: 0.45, y: 0.05 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    effects: [
      {
        id: 'fx_3d_split',
        effectId: 'lumina.chromatic_aberration',
        name: '3D Anaglyph Split',
        enabled: true,
        opacity: 0.8,
        params: { offset: 16, angle: 0 },
      },
    ],
    createdAt: '2025-01-12T12:00:00Z',
  },
  {
    id: 'duo_purple_lime',
    name: 'Cyber Purple & Electric Lime',
    category: 'duotone',
    description: 'High-voltage concert duotone with deep ultraviolet base and electric neon lime highlights.',
    author: 'VeeCut Graphic Lab',
    version: '1.2',
    scope: 'color',
    intensity: 1.0,
    rating: 4.88,
    popularityScore: 87,
    usageCount: 96000,
    tags: ['duotone', 'purple', 'lime', 'concert', 'festival', 'graphic pop'],
    previewGradient: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 50%, #84cc16 100%)',
    colorGrade: {
      ...baseGrade(),
      contrast: 1.45,
      saturation: 1.5,
      wheels: {
        lift: { r: 0.25, g: -0.15, b: 0.45, y: -0.05 },
        gamma: { r: 0.1, g: 0.2, b: 0.1, y: 0.0 },
        gain: { r: -0.1, g: 0.5, b: -0.1, y: 0.1 },
        offset: { r: 0, g: 0, b: 0, y: 0 },
      },
    },
    createdAt: '2025-01-23T12:00:00Z',
  },
];
